sqlite on scaffold only
RubricLab/create-rubric-app pull request #21
Opened 2023-11-15 21:33 UTC by iamshanvy

use sqlite prisma provider only when scaffolding the project, use postgresql by default (for demo deployment)

essentially it is just a string replacement from postgresql to sqlite of `schema.prisma` file

alternative is probably having a separate file (like `scaffold.schema.prisma`) that would be `mv`ed to scaffolded project with provider set as `sqlite`, main idea is to use sqlite only on scaffolded project

proposed solution for https://github.com/RubricLab/create-rubric-app/issues/16, open for discussion

marked as draft since I am able to test on windows only tomorrow

2023-11-16 14:00 UTC, tedspare commented
super creative approach! thanks for doing this work.

I wonder if projects scaffolded with `create-rubric-app` might still want to use `postgres` when deployed

another approach is having two schema files, `dev.prisma.schema` and `prisma.schema`, then pointing to the right file depending by env eg.

```bash
prisma generate --schema=$(if [ $NODE_ENV = 'production' ]; then echo schema.prisma; else echo dev.schema.prisma; fi)
```

would you be up to trying that approach? (this work would not be lost. iterative process)

2023-11-16 15:02 UTC, iamshanvy commented
> super creative approach! thanks for doing this work.
> 
> I wonder if projects scaffolded with `create-rubric-app` might still want to use `postgres` when deployed
> 
> another approach is having two schema files, `dev.prisma.schema` and `prisma.schema`, then pointing to the right file depending by env eg.
> 
> ```shell
> prisma generate --schema=$(if [ $NODE_ENV = 'production' ]; then echo schema.prisma; else echo dev.schema.prisma; fi)
> ```
> 
> would you be up to trying that approach? (this work would not be lost. iterative process)

you are right, after a fresh look today I think current PR is too complex for no reason, I got pigeon holed, working on changes now

2023-11-16 15:52 UTC, iamshanvy commented
@tedspare  the script does the job, but if windows support is needed then it would more complicated

I propose two solutions, have a simple db.js file to manage prisma related commands (since js code is cross platform here as opposed to bash) and as an example then run from package.json as `node db.js`

or

simply have separate scripts for dev and prod, like in package.json have it as `"db:push:dev":"..."` or `"db:push:prod":"..."`

2023-11-23 15:40 UTC, tedspare commented
> @tedspare the script does the job, but if windows support is needed then it would more complicated
> 
> I propose two solutions, have a simple db.js file to manage prisma related commands (since js code is cross platform here as opposed to bash) and as an example then run from package.json as `node db.js`
> 
> or
> 
> simply have separate scripts for dev and prod, like in package.json have it as `"db:push:dev":"..."` or `"db:push:prod":"..."`
> 
> this is already assuming that we have two prisma schemas, one for dev and for prod

the latter solution sounds clean! the `postinstall` script would also be replaced with env-specific steps eg. `"build": "db:push:prod && ..."` vs `"dev": "db:push:dev && ..."`

want to give that a try?

2023-11-23 22:17 UTC, tedspare commented on templates/agent/package.json
> +		"db:dev:push": "prisma db push --schema ./prisma/dev.schema.prisma && prisma db seed --schema ./prisma/dev.schema.prisma",
A few things from testing locally:
- Change `--schema ./path` to `--schema=./path`
- Change `dev.schema.prisma` to `dev/schema.prisma`
- Remove `db seed` command altogether (I couldn't get it to work with our TSConfig)

2023-11-23 22:19 UTC, tedspare commented on templates/agent/prisma/dev.schema.prisma
> +// This is your Prisma schema file,
See [above](https://github.com/RubricLab/create-rubric-app/pull/21/files#r1403766540); let's move this to **prisma/dev/schema.prisma**

2023-11-23 22:21 UTC, tedspare commented on templates/agent/package.json
Also, let's bump `langchain` to `"^0.0.197-rc.1"` (can simply run `bun rm langchain && bun add langchain`)

2023-11-23 22:21 UTC, tedspare requested changes
Looking clean! Added a few comments based on testing. Will test again once implemented.

2023-11-28 21:07 UTC, tedspare approved these changes
LGTM

2023-11-28 21:09 UTC, merged

2023-11-28 21:17 UTC, DexterStorey commented
kick ass work @iamshanvy - been keeping tabs on this one from the shadow realm. Excited to see this on main!